# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170124_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 24, 9, 43, 14, 928460, tzinfo=utc)),
        ),
    ]
